version: '3.3'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    networks:
      - shared_network
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse  # Persistent storage

volumes:
  clickhouse-data:
    driver: local

networks:
  shared_network:
    external: true