version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - shared_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local

networks:
  shared_network:
    external: true