version: '3.3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /var/jellyfin/config:/config
      - /var/jellyfin/data:/data
      # 如果你想要挂载媒体文件夹，可以取消下一行的注释并配置你的媒体文件夹路径
      - /mnt/d/home:/media
    ports:
      - "8096:8096"
      # 如果你需要使用 SSL，请取消下一行的注释并配置 SSL 端口
      # - "8920:8920"
    restart: unless-stopped