version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - shared_network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
    driver: local

networks:
  shared_network:
    external: true